[test]
smol = true                                      # Reduce memory usage during test runs
root = "."                                       # The root directory for test files
coverage = true
coverageThreshold = 0.9                          # to require 90% line-level and function-level coverage
coveragePathIgnorePatterns = ["**/constants/**"] # Ignore all non-test files
